// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Product struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Price int64  `json:"price"`
	Stock int32  `json:"stock"`
}
